a=int(input("enter first num:"))
b=int(input("enter second num:"))
print("sum:",a+b)
print("diff:",a-b)
print("prod:",a*b)
print("int_div:",a//b)
print("flo_div:",a/b)
print("pow:",a**b)
print("mod:",a%b)